version: '3.8'

services:
  web:
    build: .
    ports:
      - "5003:5003"
    volumes:
      - .:/app
      - data:/app/instance
    environment:
      - FLASK_ENV=development
      - MAIL_USERNAME=tu_correo@gmail.com
      - MAIL_PASSWORD=tu_password
    restart: unless-stopped

volumes:
  data:
