version: '3'

services:
  web:
    build: .
    ports:
      - "5003:5003"
    volumes:
      - .:/app
      - sqlite_data:/app/instance
    environment:
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

volumes:
  sqlite_data:
